CREATE SEQUENCE DIM_CLIENTE_ID_SEQ
INCREMENT BY
1
MINVALUE 1
MAXVALUE 999999 START 200;

CREATE TABLE DIM_CLIENTE (
SK_CLIENTE INTEGER PRIMARY KEY NOT NULL DEFAULT NEXTVAL('dim_cliente_id_seq'),
NK_CLIENTE VARCHAR(60) NOT NULL,
NM_CLIENTE VARCHAR(100) NOT NULL,
NM_EMAIL VARCHAR(100) NOT NULL
);
