INSERT INTO ST_VENDA
SELECT
PEDIDOS.DATAPEDIDO,
PEDIDOS.NUMEROPEDIDO,
ITENSPEDIDO.CODIGOPRODUTO,
ITENSPEDIDO.QUANTIDADEPEDIDO,
ITENSPEDIDO.PRECOUNITARIO,
PEDIDOS.NUMEROCLIENTE,
PEDIDOS.STATUSPEDIDO
FROM
PEDIDOS,
ITENSPEDIDO;