INSERT INTO CADASTRO_CLIENTE (CDCLI, NOMECLI, EMAILCLI)
VALUES (128, 'piton', 'suporte@raizzer.com');
INSERT INTO CADASTRO_CLIENTE (CDCLI, NOMECLI, EMAILCLI)
VALUES (2001, 'doriva', 'doriva@doriva.com');
INSERT INTO CADASTRO_CLIENTE (CDCLI, NOMECLI, EMAILCLI)
VALUES (3001, 'rigo', 'rigo@rigonis.com');
INSERT INTO CADASTRO_CLIENTE (CDCLI, NOMECLI, EMAILCLI)
VALUES (4001, 'rob', 'rob@robhud.com');