INSERT INTO LEG_PRODUTOS (CDPRODUTO, NOMEPRODUTO, CATEGORIAPRODUTO,
MEDIDAPRODUTO, FORNECEDORPRODUTO, DESCRICAOPRODUTO,
QTDESTOQUEPRODUTO, PRECOPRODUTO, STATUSPROD)
VALUES ('s24_1937', 'pizza de milho', 'pizza salgada', '45cm',
'casa das massas', 'queijo e milho', 320, 24.50, 'ativo');
INSERT INTO LEG_PRODUTOS (CDPRODUTO, NOMEPRODUTO, CATEGORIAPRODUTO,
MEDIDAPRODUTO, FORNECEDORPRODUTO, DESCRICAOPRODUTO,
QTDESTOQUEPRODUTO, PRECOPRODUTO, STATUSPROD)
VALUES ('s24_4278', 'pizza 4 queijos', 'pizza salgada', '45cm',
'casa das massas', 'queijo gorgonzola, cheddar, provolone, brie',
45, 48.81, 'ativo');
INSERT INTO LEG_PRODUTOS (CDPRODUTO, NOMEPRODUTO, CATEGORIAPRODUTO,
MEDIDAPRODUTO, FORNECEDORPRODUTO, DESCRICAOPRODUTO,
QTDESTOQUEPRODUTO, PRECOPRODUTO, STATUSPROD)
VALUES ('s18_4409', 'pizza calabresa', 'pizza salgada', '45cm',
'casa das massas', 'calabresa italiana', 22, 56.50, 'ativo');