CREATE TABLE LEG_PRODUTOS (
CDPRODUTO VARCHAR(50) NOT NULL,
NOMEPRODUTO VARCHAR(70) NOT NULL,
CATEGORIAPRODUTO VARCHAR(50) NOT NULL,
MEDIDAPRODUTO VARCHAR(10) NOT NULL,
FORNECEDORPRODUTO VARCHAR(50) NOT NULL,
DESCRICAOPRODUTO TEXT NOT NULL,
QTDESTOQUEPRODUTO INTEGER NOT NULL,
PRECOPRODUTO NUMERIC(10, 4) NOT NULL,
STATUSPROD VARCHAR(100) NOT NULL,
CONSTRAINT LEG_PRODUTOS_PK PRIMARY KEY (CDPRODUTO)
);