CREATE TABLE ITENSPEDIDO (
NUMEROPEDIDO INTEGER NOT NULL,
CODIGOPRODUTO VARCHAR(50) NOT NULL,
QUANTIDADEPEDIDO INTEGER NOT NULL,
PRECOUNITARIO DOUBLE PRECISION NOT NULL,
NUMEROLINHAPEDIDO SMALLINT NOT NULL,
PRIMARY KEY (NUMEROPEDIDO, CODIGOPRODUTO)
);